panda_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  solve_type: Distance
  position_only_ik: true
  kinematics_solver_timeout: 0.01
